//! Sending the reply to a remote method call.

use futures::{FutureExt, ready};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::{
    future::Future,
    pin::Pin,
    task::{Context, Poll},
};

use crate::{
    codec,
    rch::{Sending, SendingError, oneshot},
};

/// The type a method's return value is transferred as.
///
/// This is a projection rather than the type itself, because the return type of
/// a method is taken as written in the trait, which may be an alias, and thus
/// cannot be taken apart by the [`remote`](super::remote) macro.
#[doc(hidden)]
pub type Reply<R> = <R as IsReply>::Compact;

/// A method return type, which is always a [`Result`].
#[doc(hidden)]
pub trait IsReply: Sized {
    /// The type the value is transferred as.
    type Compact: From<Self> + Into<Self>;

    /// The same return type with its value replaced by `()`.
    ///
    /// This is used when the caller is not interested in the value of the call, but
    /// only in whether it failed.
    type WithoutValue: IsReply;

    /// Whether the method returned an error.
    fn is_error(&self) -> bool;

    /// Builds the return value from a failure of the call itself.
    fn from_call_error(err: super::CallError) -> Self;

    /// The successful return value without a value.
    fn without_value() -> Self::WithoutValue;
}

impl<T, E> IsReply for Result<T, E>
where
    E: From<super::CallError>,
{
    type Compact = crate::versioned::result::Result<T, E>;
    type WithoutValue = Result<(), E>;

    fn is_error(&self) -> bool {
        self.is_err()
    }

    fn from_call_error(err: super::CallError) -> Self {
        Err(err.into())
    }

    fn without_value() -> Result<(), E> {
        Ok(())
    }
}

/// The return type of a method that can hand over a [request receiver](super::ReqReceiver).
///
/// This is implemented for every `Result<T, E>` where `T` is the [client](super::Client)
/// of a remotable trait. It is a projection rather than the types themselves, because the
/// return type of a method is taken as written in the trait, which may be an alias, and
/// thus cannot be taken apart by the [`remote`](super::remote) macro.
#[doc(hidden)]
pub trait IsPipelinableReply: IsReply {
    /// The client returned by the method.
    type Client;

    /// The request receiver of the returned client.
    type ReqReceiver;

    /// Splits into the returned client, or the error converted into the return type
    /// of the method taking the request receiver.
    fn split(self) -> Result<Self::Client, Self::WithoutValue>;

    /// Converts into the return type of the method taking the request receiver,
    /// discarding the returned client.
    fn into_without_value(self) -> Self::WithoutValue {
        match self.split() {
            Ok(_client) => Self::without_value(),
            Err(without_value) => without_value,
        }
    }
}

impl<T, E> IsPipelinableReply for Result<T, E>
where
    T: super::Client,
    E: From<super::CallError>,
{
    type Client = T;
    type ReqReceiver = T::ReqReceiver;

    fn split(self) -> Result<T, Result<(), E>> {
        match self {
            Ok(client) => Ok(client),
            Err(err) => Err(Err(err)),
        }
    }
}

/// Sends the reply to a remote method call.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro. Send the return value of the method to
/// reply to the call; dropping this without sending makes the call fail at the
/// caller.
pub struct ReplySender<R, Codec = codec::Default>(oneshot::Sender<Reply<R>, Codec>)
where
    R: IsReply;

/// Creates a channel for replying to a remote method call.
#[doc(hidden)]
pub fn reply_channel<R, Codec>(
    max_item_size: usize,
) -> (ReplySender<R, Codec>, oneshot::Receiver<Reply<R>, Codec>)
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    let (mut tx, rx) = oneshot::channel();
    tx.set_max_item_size(max_item_size);
    (ReplySender(tx), rx)
}

impl<R, Codec> std::fmt::Debug for ReplySender<R, Codec>
where
    R: IsReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ReplySender").finish()
    }
}

impl<R, Codec> ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Sends the reply over this channel.
    ///
    /// `Ok` means that the reply was queued for sending; the returned handle
    /// reports whether it was sent.
    pub fn send(self, reply: R) -> Result<Sending<Reply<R>>, oneshot::SendError<R>> {
        self.0.send(reply.into()).map_err(|err| match err {
            oneshot::SendError::Closed(reply) => oneshot::SendError::Closed(reply.into()),
            oneshot::SendError::Dropped => oneshot::SendError::Dropped,
            oneshot::SendError::Failed => oneshot::SendError::Failed,
        })
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        self.0.closed().await
    }

    /// Returns whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        self.0.is_closed()
    }

    /// The maximum size of the reply in bytes.
    ///
    /// A reply exceeding this is not sent.
    pub fn max_item_size(&self) -> usize {
        self.0.max_item_size()
    }
}

impl<R, Codec> Serialize for ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(serializer)
    }
}

impl<'de, R, Codec> Deserialize<'de> for ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(Self(oneshot::Sender::deserialize(deserializer)?))
    }
}

/// Where the result of a remote method call is delivered.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro.
///
/// Use [complete](Self::complete) to send the result.
///
/// Dropping this without sending makes the call fail at the caller.
pub struct ReplyTo<R, Codec = codec::Default>
where
    R: IsReply,
{
    /// Channel the reply is sent over.
    tx: ReplySender<R, Codec>,
    /// Whether the server may dispatch the call on its own task.
    allow_spawn: bool,
    /// Whether the server shall stop serving when the call fails.
    stop_on_error: bool,
}

impl<R, Codec> std::fmt::Debug for ReplyTo<R, Codec>
where
    R: IsReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ReplyTo")
            .field("allow_spawn", &self.allow_spawn)
            .field("stop_on_error", &self.stop_on_error)
            .finish()
    }
}

impl<R, Codec> From<ReplySender<R, Codec>> for ReplyTo<R, Codec>
where
    R: IsReply,
{
    fn from(reply_tx: ReplySender<R, Codec>) -> Self {
        Self { tx: reply_tx, allow_spawn: true, stop_on_error: false }
    }
}

impl<R, Codec> From<ReplyTo<R, Codec>> for ReplySender<R, Codec>
where
    R: IsReply,
{
    fn from(reply_to: ReplyTo<R, Codec>) -> Self {
        reply_to.tx
    }
}

impl<R, Codec> ReplyTo<R, Codec>
where
    R: IsReply,
{
    /// Creates a new reply target with the specified call options.
    #[doc(hidden)]
    pub fn new(tx: ReplySender<R, Codec>, allow_spawn: bool, stop_on_error: bool) -> Self {
        Self { tx, allow_spawn, stop_on_error }
    }

    /// Whether the server may dispatch the call on its own task.
    pub fn allow_spawn(&self) -> bool {
        self.allow_spawn
    }

    /// Whether the server shall stop serving when the call fails.
    pub fn stop_on_error(&self) -> bool {
        self.stop_on_error
    }
}

impl<R, Codec> ReplyTo<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Completes the call with the result of the method.
    ///
    /// The reply is queued for sending; the returned handle reports whether it was
    /// transmitted and may be discarded.
    pub async fn complete(self, result: R) -> Sending<Reply<R>> {
        self.send(result).unwrap_or_else(|_| Sending::dropped())
    }

    /// Sends the reply over this channel.
    ///
    /// `Ok` means that the reply was queued for sending; the returned handle
    /// reports whether it was sent.
    pub fn send(self, reply: R) -> Result<Sending<Reply<R>>, oneshot::SendError<R>> {
        self.tx.send(reply)
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        self.tx.closed().await
    }

    /// Whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        self.tx.is_closed()
    }

    /// The maximum allowed size of the reply in bytes.
    pub fn max_item_size(&self) -> usize {
        self.tx.max_item_size()
    }

    /// Returns the underlying reply sender.
    pub fn into_sender(self) -> ReplySender<R, Codec> {
        self.tx
    }
}

// The transported representation of [`ReplyTo`] and [`PipelinableReplyTo`].
//
// Both use the same representation, so that a method can gain the `#[pipelinable]`
// attribute without changing the encoding of its requests.
//
// `Rx` is the request receiver the call may hand over; it is `()` for a method that
// cannot be pipelined.
//
// Endpoints of Remoc versions before 0.20 expect the bare reply sender, thus the old
// representation is that. A request that uses any of the options has no old
// representation and fails to serialize for such an endpoint.
mod transported {
    use super::*;

    /// Reply channel of a transported reply, for serialization.
    #[derive(Serialize)]
    #[serde(bound = "")]
    pub enum SenderRef<'transport, R, Codec>
    where
        R: IsReply,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        Full(&'transport ReplySender<R, Codec>),
        #[serde(rename = "_1")]
        WithoutValue(&'transport ReplySender<<R as IsReply>::WithoutValue, Codec>),
    }

    /// Reply channel of a transported reply, for deserialization.
    #[derive(Deserialize)]
    #[serde(bound = "")]
    pub enum Sender<R, Codec>
    where
        R: IsReply,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        Full(ReplySender<R, Codec>),
        #[serde(rename = "_1")]
        WithoutValue(ReplySender<<R as IsReply>::WithoutValue, Codec>),
    }

    /// Transported reply, for serialization.
    #[derive(Serialize)]
    #[serde(bound = "")]
    pub struct ReplyRef<'transport, R, Rx, Codec>
    where
        R: IsReply,
        Rx: crate::RemoteSend,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        pub tx: SenderRef<'transport, R, Codec>,
        #[serde(rename = "_1")]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub req_rx: Option<&'transport Rx>,
        #[serde(rename = "_2")]
        #[serde(skip_serializing_if = "is_true")]
        pub allow_spawn: bool,
        #[serde(rename = "_3")]
        #[serde(skip_serializing_if = "is_false")]
        pub stop_on_error: bool,
    }

    /// Transported reply, for deserialization.
    #[derive(Deserialize)]
    #[serde(bound = "")]
    pub struct TransportedReply<R, Rx, Codec>
    where
        R: IsReply,
        Rx: crate::RemoteSend,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        pub tx: Sender<R, Codec>,
        #[serde(rename = "_1")]
        #[serde(default = "none")]
        pub req_rx: Option<Rx>,
        #[serde(rename = "_2")]
        #[serde(default = "yes")]
        pub allow_spawn: bool,
        #[serde(rename = "_3")]
        #[serde(default)]
        pub stop_on_error: bool,
    }

    pub fn is_true(value: &bool) -> bool {
        *value
    }

    pub fn is_false(value: &bool) -> bool {
        !*value
    }

    pub fn yes() -> bool {
        true
    }

    pub fn none<T>() -> Option<T> {
        None
    }

    /// The request uses an option that the remote endpoint does not support.
    pub fn unsupported() -> crate::versioned::Error {
        "the remote endpoint does not support the options of this method call".into()
    }

    /// The request combines a reply channel and a request receiver in a way that is
    /// not supported.
    pub fn unsupported_combination() -> crate::versioned::Error {
        "unsupported combination of reply channel and request receiver".into()
    }
}

// Serialization of [`ReplyTo`].
impl<R, Codec> crate::versioned::Versioned for ReplyTo<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
    Codec: codec::Codec,
{
    type Versioner = crate::versioned::compact::CompactVersioner;

    type CurrentRef<'transport>
        = transported::ReplyRef<'transport, R, (), Codec>
    where
        Self: 'transport;

    fn as_current<'transport>(&'transport self) -> Result<Self::CurrentRef<'transport>, crate::versioned::Error> {
        Ok(transported::ReplyRef {
            tx: transported::SenderRef::Full(&self.tx),
            req_rx: None,
            allow_spawn: self.allow_spawn,
            stop_on_error: self.stop_on_error,
        })
    }

    type Current = transported::TransportedReply<R, (), Codec>;

    fn from_current(current: Self::Current) -> Result<Self, crate::versioned::Error> {
        let transported::TransportedReply { tx, req_rx, allow_spawn, stop_on_error } = current;
        match (tx, req_rx) {
            (transported::Sender::Full(tx), None) => Ok(Self { tx, allow_spawn, stop_on_error }),
            _ => Err(transported::unsupported_combination()),
        }
    }

    type OldRef<'transport>
        = &'transport ReplySender<R, Codec>
    where
        Self: 'transport;

    fn as_old<'transport>(&'transport self) -> Result<Self::OldRef<'transport>, crate::versioned::Error> {
        if !self.allow_spawn || self.stop_on_error {
            return Err(transported::unsupported());
        }

        Ok(&self.tx)
    }

    type Old = ReplySender<R, Codec>;

    fn from_old(old: Self::Old) -> Result<Self, crate::versioned::Error> {
        Ok(Self::from(old))
    }
}

crate::impl_serde! {
    ReplyTo<R, Codec>
    where
        R: IsReply + 'static,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
        Codec: codec::Codec
}

/// Where the result of a remote method call is delivered for a pipelinable method.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro for a trait method that
/// carries the `#[pipelinable]` attribute.
///
/// Use [complete](Self::complete) to send the result.
///
/// Dropping this without sending makes the call fail at the caller.
pub enum PipelinableReplyTo<R, Codec = codec::Default>
where
    R: IsPipelinableReply,
{
    /// Send the result of the method back to the caller.
    Normal(ReplyTo<R, Codec>),
    /// Let the client returned by the method execute the requests of `req_rx`,
    /// then send the client back to the caller.
    Pipeline {
        /// Requests that the client returned by the method should execute.
        req_rx: R::ReqReceiver,
        /// Channel for sending the result once all requests have been executed.
        ///
        /// The client is [`None`] when the object was consumed by a method taking
        /// `self` by value.
        reply_tx: ReplyTo<<R as IsReply>::WithoutValue, Codec>,
    },
}

impl<R, Codec> std::fmt::Debug for PipelinableReplyTo<R, Codec>
where
    R: IsPipelinableReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal(_) => f.debug_tuple("Normal").finish(),
            Self::Pipeline { .. } => f.debug_struct("Pipeline").finish(),
        }
    }
}

impl<R, Codec> PipelinableReplyTo<R, Codec>
where
    R: IsPipelinableReply,
{
    /// Whether the server may dispatch the call on its own task.
    pub fn allow_spawn(&self) -> bool {
        match self {
            Self::Normal(reply_to) => reply_to.allow_spawn(),
            Self::Pipeline { reply_tx, .. } => reply_tx.allow_spawn(),
        }
    }

    /// Whether the server shall stop serving when the call fails.
    pub fn stop_on_error(&self) -> bool {
        match self {
            Self::Normal(reply_to) => reply_to.stop_on_error(),
            Self::Pipeline { reply_tx, .. } => reply_tx.stop_on_error(),
        }
    }
}

impl<R, Codec> PipelinableReplyTo<R, Codec>
where
    R: IsPipelinableReply,
    Reply<R>: crate::RemoteSend,
    Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Completes the call with the result of the method.
    ///
    /// For [`Normal`](Self::Normal) the result is sent to the caller.
    ///
    /// For [`Pipeline`](Self::Pipeline) the returned client executes the requests of
    /// the handed over request receiver in the background; an error result is passed
    /// through unchanged. This returns as soon as serving has been started.
    ///
    /// The reply itself is only queued for sending; the returned handle reports whether
    /// it was transmitted and may be discarded.
    pub async fn complete(self, result: R) -> Completing<R>
    where
        <R as IsPipelinableReply>::ReqReceiver: super::ReqReceiver<Codec>
            + super::ServerBase<Client = <R as IsPipelinableReply>::Client>
            + Send
            + 'static,
        <R as IsPipelinableReply>::Client: Send + 'static,
    {
        match self {
            Self::Normal(reply_tx) => {
                Completing::Normal(reply_tx.send(result).unwrap_or_else(|_| Sending::dropped()))
            }
            Self::Pipeline { req_rx, reply_tx } => {
                let pipelined = match result.split() {
                    Ok(client) => {
                        // Serving continues in the background, so that the caller can
                        // keep using its client for as long as it likes.
                        crate::rtc::spawn(tracing::Instrument::in_current_span(async move {
                            let _ = super::ReqReceiver::forward(req_rx, client).await;
                        }));
                        R::without_value()
                    }
                    Err(pipelined) => pipelined,
                };

                Completing::Pipeline(reply_tx.send(pipelined).unwrap_or_else(|_| Sending::dropped()))
            }
        }
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        match self {
            Self::Normal(reply_tx) => reply_tx.closed().await,
            Self::Pipeline { reply_tx, .. } => reply_tx.closed().await,
        }
    }

    /// Whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        match self {
            Self::Normal(reply_tx) => reply_tx.is_closed(),
            Self::Pipeline { reply_tx, .. } => reply_tx.is_closed(),
        }
    }

    /// Whether a request receiver was handed over, i.e. this is
    /// [`Pipeline`](Self::Pipeline).
    pub fn is_pipelined(&self) -> bool {
        matches!(self, Self::Pipeline { .. })
    }
}

// Serialization of [`PipelinableReplyTo`], using the same representation as
// [`ReplyTo`], see there.
impl<R, Codec> crate::versioned::Versioned for PipelinableReplyTo<R, Codec>
where
    R: IsPipelinableReply,
    <R as IsPipelinableReply>::ReqReceiver: crate::RemoteSend,
    Reply<R>: crate::RemoteSend,
    Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
    Codec: codec::Codec,
{
    type Versioner = crate::versioned::compact::CompactVersioner;

    type CurrentRef<'transport>
        = transported::ReplyRef<'transport, R, <R as IsPipelinableReply>::ReqReceiver, Codec>
    where
        Self: 'transport;

    fn as_current<'transport>(&'transport self) -> Result<Self::CurrentRef<'transport>, crate::versioned::Error> {
        Ok(match self {
            Self::Normal(reply_to) => transported::ReplyRef {
                tx: transported::SenderRef::Full(&reply_to.tx),
                req_rx: None,
                allow_spawn: reply_to.allow_spawn,
                stop_on_error: reply_to.stop_on_error,
            },
            Self::Pipeline { req_rx, reply_tx } => transported::ReplyRef {
                tx: transported::SenderRef::WithoutValue(&reply_tx.tx),
                req_rx: Some(req_rx),
                allow_spawn: reply_tx.allow_spawn,
                stop_on_error: reply_tx.stop_on_error,
            },
        })
    }

    type Current = transported::TransportedReply<R, <R as IsPipelinableReply>::ReqReceiver, Codec>;

    fn from_current(current: Self::Current) -> Result<Self, crate::versioned::Error> {
        let transported::TransportedReply { tx, req_rx, allow_spawn, stop_on_error } = current;
        match (tx, req_rx) {
            (transported::Sender::Full(tx), None) => Ok(Self::Normal(ReplyTo { tx, allow_spawn, stop_on_error })),
            (transported::Sender::WithoutValue(tx), Some(req_rx)) => {
                Ok(Self::Pipeline { req_rx, reply_tx: ReplyTo { tx, allow_spawn, stop_on_error } })
            }
            _ => Err(transported::unsupported_combination()),
        }
    }

    type OldRef<'transport>
        = &'transport ReplySender<R, Codec>
    where
        Self: 'transport;

    fn as_old<'transport>(&'transport self) -> Result<Self::OldRef<'transport>, crate::versioned::Error> {
        match self {
            Self::Normal(reply_to) => crate::versioned::Versioned::as_old(reply_to),
            Self::Pipeline { .. } => Err(transported::unsupported()),
        }
    }

    type Old = ReplySender<R, Codec>;

    fn from_old(old: Self::Old) -> Result<Self, crate::versioned::Error> {
        Ok(Self::Normal(ReplyTo::from(old)))
    }
}

crate::impl_serde! {
    PipelinableReplyTo<R, Codec>
    where
        R: IsPipelinableReply + 'static,
        <R as IsPipelinableReply>::ReqReceiver: crate::RemoteSend,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsReply>::WithoutValue>: crate::RemoteSend,
        Codec: codec::Codec
}

/// Handle to obtain the result of [completing](PipelinableReplyTo::complete) a call.
///
/// Await this handle to obtain the result of transmitting the reply. This is optional
/// and only necessary if you want to explicitly handle errors that can occur while
/// sending.
///
/// You *should not* delay the receipt of further requests by awaiting this handle.
/// Dropping it *does not* abort transmitting the reply; a failure caused by the reply
/// itself, such as a serialization error, is logged in that case.
pub enum Completing<R>
where
    R: IsPipelinableReply,
{
    /// The reply of an ordinary call is being transmitted.
    Normal(Sending<Reply<R>>),
    /// The reply of a pipelined call is being transmitted.
    Pipeline(Sending<Reply<<R as IsReply>::WithoutValue>>),
}

impl<R> std::fmt::Debug for Completing<R>
where
    R: IsPipelinableReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal(_) => f.debug_tuple("Normal").finish(),
            Self::Pipeline(_) => f.debug_tuple("Pipeline").finish(),
        }
    }
}

impl<R> Future for Completing<R>
where
    R: IsPipelinableReply,
{
    type Output = Result<(), SendingError<<R as IsReply>::WithoutValue>>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        let res = match self.get_mut() {
            Self::Normal(sending) => ready!(sending.poll_unpin(cx))
                .map_err(|err| err.map_item(|reply| Into::<R>::into(reply).into_without_value())),
            Self::Pipeline(sending) => ready!(sending.poll_unpin(cx))
                .map_err(|err| err.map_item(Into::<<R as IsReply>::WithoutValue>::into)),
        };
        Poll::Ready(res)
    }
}
