//! Sending the reply to a remote method call.

use futures::{FutureExt, ready};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::{
    future::Future,
    pin::Pin,
    task::{Context, Poll},
};

use crate::{
    codec,
    rch::{Sending, SendingError, oneshot},
};

/// The type a method's return value is transferred as.
///
/// This is a projection rather than the type itself, because the return type of
/// a method is taken as written in the trait, which may be an alias, and thus
/// cannot be taken apart by the [`remote`](super::remote) macro.
#[doc(hidden)]
pub type Reply<R> = <R as IsReply>::Compact;

/// A method return type, which is always a [`Result`].
#[doc(hidden)]
pub trait IsReply: Sized {
    /// The type the value is transferred as.
    type Compact: From<Self> + Into<Self>;

    /// Whether the method returned an error.
    fn is_error(&self) -> bool;

    /// Builds the return value from a failure of the call itself.
    fn from_call_error(err: super::CallError) -> Self;
}

impl<T, E> IsReply for Result<T, E>
where
    E: From<super::CallError>,
{
    type Compact = crate::versioned::result::Result<T, E>;

    fn is_error(&self) -> bool {
        self.is_err()
    }

    fn from_call_error(err: super::CallError) -> Self {
        Err(err.into())
    }
}

/// The return type of a method that can hand over a [request receiver](super::ReqReceiver).
///
/// This is implemented for every `Result<T, E>` where `T` is the [client](super::Client)
/// of a remotable trait. It is a projection rather than the types themselves, because the
/// return type of a method is taken as written in the trait, which may be an alias, and
/// thus cannot be taken apart by the [`remote`](super::remote) macro.
#[doc(hidden)]
pub trait IsPipelinableReply: IsReply {
    /// The client returned by the method.
    type Client;

    /// The request receiver of the returned client.
    type ReqReceiver;

    /// The return type of the generated method taking the request receiver.
    ///
    /// This is `Result<Option<T>, E>`, since the object may be consumed by a method
    /// taking `self` by value while its requests are served.
    type Pipelined: IsReply;

    /// Splits into the returned client, or the error converted into the return type
    /// of the method taking the request receiver.
    fn split(self) -> Result<Self::Client, Self::Pipelined>;

    /// Builds the return value of the method taking the request receiver.
    ///
    /// `client` is [`None`] when the object was consumed while serving.
    fn pipelined(client: Option<Self::Client>) -> Self::Pipelined;

    /// Converts into the return type of the method taking the request receiver.
    fn into_pipelined(self) -> Self::Pipelined {
        match self.split() {
            Ok(client) => Self::pipelined(Some(client)),
            Err(pipelined) => pipelined,
        }
    }
}

impl<T, E> IsPipelinableReply for Result<T, E>
where
    T: super::Client,
    E: From<super::CallError>,
{
    type Client = T;
    type ReqReceiver = T::ReqReceiver;
    type Pipelined = Result<Option<T>, E>;

    fn split(self) -> Result<T, Result<Option<T>, E>> {
        match self {
            Ok(client) => Ok(client),
            Err(err) => Err(Err(err)),
        }
    }

    fn pipelined(client: Option<T>) -> Result<Option<T>, E> {
        Ok(client)
    }
}

/// Sends the reply to a remote method call.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro. Send the return value of the method to
/// reply to the call; dropping this without sending makes the call fail at the
/// caller.
pub struct ReplySender<R, Codec = codec::Default>(oneshot::Sender<Reply<R>, Codec>)
where
    R: IsReply;

/// Creates a channel for replying to a remote method call.
#[doc(hidden)]
pub fn reply_channel<R, Codec>(
    max_item_size: usize,
) -> (ReplySender<R, Codec>, oneshot::Receiver<Reply<R>, Codec>)
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    let (mut tx, rx) = oneshot::channel();
    tx.set_max_item_size(max_item_size);
    (ReplySender(tx), rx)
}

impl<R, Codec> std::fmt::Debug for ReplySender<R, Codec>
where
    R: IsReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ReplySender").finish()
    }
}

impl<R, Codec> ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Sends the reply over this channel.
    ///
    /// `Ok` means that the reply was queued for sending; the returned handle
    /// reports whether it was sent.
    pub fn send(self, reply: R) -> Result<Sending<Reply<R>>, oneshot::SendError<R>> {
        self.0.send(reply.into()).map_err(|err| match err {
            oneshot::SendError::Closed(reply) => oneshot::SendError::Closed(reply.into()),
            oneshot::SendError::Dropped => oneshot::SendError::Dropped,
            oneshot::SendError::Failed => oneshot::SendError::Failed,
        })
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        self.0.closed().await
    }

    /// Returns whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        self.0.is_closed()
    }

    /// The maximum size of the reply in bytes.
    ///
    /// A reply exceeding this is not sent.
    pub fn max_item_size(&self) -> usize {
        self.0.max_item_size()
    }
}

impl<R, Codec> Serialize for ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(serializer)
    }
}

impl<'de, R, Codec> Deserialize<'de> for ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(Self(oneshot::Sender::deserialize(deserializer)?))
    }
}

/// Where the result of a remote method call is delivered.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro.
///
/// Use [complete](Self::complete) to send the result.
///
/// Dropping this without sending makes the call fail at the caller.
pub struct ReplyTo<R, Codec = codec::Default>(ReplySender<R, Codec>)
where
    R: IsReply;

impl<R, Codec> std::fmt::Debug for ReplyTo<R, Codec>
where
    R: IsReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ReplyTo").finish()
    }
}

impl<R, Codec> From<ReplySender<R, Codec>> for ReplyTo<R, Codec>
where
    R: IsReply,
{
    fn from(reply_tx: ReplySender<R, Codec>) -> Self {
        Self(reply_tx)
    }
}

impl<R, Codec> From<ReplyTo<R, Codec>> for ReplySender<R, Codec>
where
    R: IsReply,
{
    fn from(reply_to: ReplyTo<R, Codec>) -> Self {
        reply_to.0
    }
}

impl<R, Codec> ReplyTo<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Completes the call with the result of the method.
    ///
    /// The reply is queued for sending; the returned handle reports whether it was
    /// transmitted and may be discarded.
    pub async fn complete(self, result: R) -> Sending<Reply<R>> {
        self.send(result).unwrap_or_else(|_| Sending::dropped())
    }

    /// Sends the reply over this channel.
    ///
    /// `Ok` means that the reply was queued for sending; the returned handle
    /// reports whether it was sent.
    pub fn send(self, reply: R) -> Result<Sending<Reply<R>>, oneshot::SendError<R>> {
        self.0.send(reply)
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        self.0.closed().await
    }

    /// Whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        self.0.is_closed()
    }

    /// The maximum allowed size of the reply in bytes.
    pub fn max_item_size(&self) -> usize {
        self.0.max_item_size()
    }

    /// Returns the underlying reply sender.
    pub fn into_sender(self) -> ReplySender<R, Codec> {
        self.0
    }
}

// The transported representation is an enum with a single variant, so that a method
// can gain the `#[pipelinable]` attribute, which turns this into a
// [`PipelinableReplyTo`], without changing the encoding of its requests.
//
// Endpoints of Remoc versions before 0.20 expect the bare reply sender, thus the old
// representation is that.
mod reply_to_versioned {
    use super::*;

    #[derive(Serialize)]
    #[serde(bound = "")]
    pub enum CurrentRef<'transport, R, Codec>
    where
        R: IsReply,
        Reply<R>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        Normal(&'transport ReplySender<R, Codec>),
    }

    #[derive(Deserialize)]
    #[serde(bound = "")]
    pub enum Current<R, Codec>
    where
        R: IsReply,
        Reply<R>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        Normal(ReplySender<R, Codec>),
    }

    impl<R, Codec> crate::versioned::Versioned for ReplyTo<R, Codec>
    where
        R: IsReply,
        Reply<R>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        type Versioner = crate::versioned::compact::CompactVersioner;

        type CurrentRef<'transport>
            = CurrentRef<'transport, R, Codec>
        where
            Self: 'transport;

        fn as_current<'transport>(
            &'transport self,
        ) -> Result<Self::CurrentRef<'transport>, crate::versioned::Error> {
            Ok(CurrentRef::Normal(&self.0))
        }

        type Current = Current<R, Codec>;

        fn from_current(current: Self::Current) -> Result<Self, crate::versioned::Error> {
            let Current::Normal(reply_tx) = current;
            Ok(Self(reply_tx))
        }

        type OldRef<'transport>
            = &'transport ReplySender<R, Codec>
        where
            Self: 'transport;

        fn as_old<'transport>(&'transport self) -> Result<Self::OldRef<'transport>, crate::versioned::Error> {
            Ok(&self.0)
        }

        type Old = ReplySender<R, Codec>;

        fn from_old(old: Self::Old) -> Result<Self, crate::versioned::Error> {
            Ok(Self(old))
        }
    }

    crate::impl_serde! {
        ReplyTo<R, Codec>
        where R: IsReply + 'static, Reply<R>: crate::RemoteSend, Codec: codec::Codec
    }
}

/// Where the result of a remote method call is delivered for a pipelinable method.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro for a trait method that
/// carries the `#[pipelinable]` attribute.
///
/// Use [complete](Self::complete) to send the result.
///
/// Dropping this without sending makes the call fail at the caller.
pub enum PipelinableReplyTo<R, Codec = codec::Default>
where
    R: IsPipelinableReply,
{
    /// Send the result of the method back to the caller.
    Normal(ReplySender<R, Codec>),
    /// Let the client returned by the method execute the requests of `req_rx`,
    /// then send the client back to the caller.
    Pipeline {
        /// Requests that the client returned by the method should execute.
        req_rx: R::ReqReceiver,
        /// Channel for sending the result once all requests have been executed.
        ///
        /// The client is [`None`] when the object was consumed by a method taking
        /// `self` by value.
        reply_tx: ReplySender<<R as IsPipelinableReply>::Pipelined, Codec>,
    },
}

impl<R, Codec> std::fmt::Debug for PipelinableReplyTo<R, Codec>
where
    R: IsPipelinableReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal(_) => f.debug_tuple("Normal").finish(),
            Self::Pipeline { .. } => f.debug_struct("Pipeline").finish(),
        }
    }
}

impl<R, Codec> PipelinableReplyTo<R, Codec>
where
    R: IsPipelinableReply,
    Reply<R>: crate::RemoteSend,
    Reply<<R as IsPipelinableReply>::Pipelined>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Completes the call with the result of the method.
    ///
    /// For [`Normal`](Self::Normal) the result is sent to the caller.
    ///
    /// For [`Pipeline`](Self::Pipeline) the returned client executes the requests of
    /// the handed over request receiver and is then sent to the caller; an error
    /// result is passed through unchanged. This does not return until every client
    /// connected to the request receiver has been dropped.
    ///
    /// The reply itself is only queued for sending; the returned handle reports whether
    /// it was transmitted and may be discarded.
    pub async fn complete(self, result: R) -> Completing<R>
    where
        <R as IsPipelinableReply>::ReqReceiver:
            super::ReqReceiver<Codec> + super::ServerBase<Client = <R as IsPipelinableReply>::Client>,
    {
        match self {
            Self::Normal(reply_tx) => {
                Completing::Normal(reply_tx.send(result).unwrap_or_else(|_| Sending::dropped()))
            }
            Self::Pipeline { req_rx, reply_tx } => {
                let pipelined = match result.split() {
                    Ok(client) => match super::ReqReceiver::forward(req_rx, client).await {
                        Ok(client) => R::pipelined(client),
                        Err(err) => <R as IsPipelinableReply>::Pipelined::from_call_error(err.into()),
                    },
                    Err(pipelined) => pipelined,
                };

                Completing::Pipeline(reply_tx.send(pipelined).unwrap_or_else(|_| Sending::dropped()))
            }
        }
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        match self {
            Self::Normal(reply_tx) => reply_tx.closed().await,
            Self::Pipeline { reply_tx, .. } => reply_tx.closed().await,
        }
    }

    /// Whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        match self {
            Self::Normal(reply_tx) => reply_tx.is_closed(),
            Self::Pipeline { reply_tx, .. } => reply_tx.is_closed(),
        }
    }

    /// Whether a request receiver was handed over, i.e. this is
    /// [`Pipeline`](Self::Pipeline).
    pub fn is_pipelined(&self) -> bool {
        matches!(self, Self::Pipeline { .. })
    }
}

// The transported representation mirrors that of [`ReplyTo`], with an additional
// variant, so that a method can gain the `#[pipelinable]` attribute without changing
// the encoding of its ordinary requests.
//
// Endpoints of Remoc versions before 0.20 expect the bare reply sender, thus the old
// representation is that. A pipelined request has no old representation and fails to
// serialize for such an endpoint.
mod pipelinable_reply_to_versioned {
    use super::*;

    #[derive(Serialize)]
    #[serde(bound = "")]
    pub enum CurrentRef<'transport, R, Codec>
    where
        R: IsPipelinableReply,
        <R as IsPipelinableReply>::ReqReceiver: crate::RemoteSend,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsPipelinableReply>::Pipelined>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        Normal(&'transport ReplySender<R, Codec>),
        #[serde(rename = "_1")]
        Pipeline {
            #[serde(rename = "_0")]
            req_rx: &'transport <R as IsPipelinableReply>::ReqReceiver,
            #[serde(rename = "_1")]
            reply_tx: &'transport ReplySender<<R as IsPipelinableReply>::Pipelined, Codec>,
        },
    }

    #[derive(Deserialize)]
    #[serde(bound = "")]
    pub enum Current<R, Codec>
    where
        R: IsPipelinableReply,
        <R as IsPipelinableReply>::ReqReceiver: crate::RemoteSend,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsPipelinableReply>::Pipelined>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        #[serde(rename = "_0")]
        Normal(ReplySender<R, Codec>),
        #[serde(rename = "_1")]
        Pipeline {
            #[serde(rename = "_0")]
            req_rx: <R as IsPipelinableReply>::ReqReceiver,
            #[serde(rename = "_1")]
            reply_tx: ReplySender<<R as IsPipelinableReply>::Pipelined, Codec>,
        },
    }

    impl<R, Codec> crate::versioned::Versioned for PipelinableReplyTo<R, Codec>
    where
        R: IsPipelinableReply,
        <R as IsPipelinableReply>::ReqReceiver: crate::RemoteSend,
        Reply<R>: crate::RemoteSend,
        Reply<<R as IsPipelinableReply>::Pipelined>: crate::RemoteSend,
        Codec: codec::Codec,
    {
        type Versioner = crate::versioned::compact::CompactVersioner;

        type CurrentRef<'transport>
            = CurrentRef<'transport, R, Codec>
        where
            Self: 'transport;

        fn as_current<'transport>(
            &'transport self,
        ) -> Result<Self::CurrentRef<'transport>, crate::versioned::Error> {
            Ok(match self {
                Self::Normal(reply_tx) => CurrentRef::Normal(reply_tx),
                Self::Pipeline { req_rx, reply_tx } => CurrentRef::Pipeline { req_rx, reply_tx },
            })
        }

        type Current = Current<R, Codec>;

        fn from_current(current: Self::Current) -> Result<Self, crate::versioned::Error> {
            Ok(match current {
                Current::Normal(reply_tx) => Self::Normal(reply_tx),
                Current::Pipeline { req_rx, reply_tx } => Self::Pipeline { req_rx, reply_tx },
            })
        }

        type OldRef<'transport>
            = &'transport ReplySender<R, Codec>
        where
            Self: 'transport;

        fn as_old<'transport>(&'transport self) -> Result<Self::OldRef<'transport>, crate::versioned::Error> {
            match self {
                Self::Normal(reply_tx) => Ok(reply_tx),
                Self::Pipeline { .. } => {
                    Err("the remote endpoint does not support pipelined method calls".into())
                }
            }
        }

        type Old = ReplySender<R, Codec>;

        fn from_old(old: Self::Old) -> Result<Self, crate::versioned::Error> {
            Ok(Self::Normal(old))
        }
    }

    crate::impl_serde! {
        PipelinableReplyTo<R, Codec>
        where
            R: IsPipelinableReply + 'static,
            <R as IsPipelinableReply>::ReqReceiver: crate::RemoteSend,
            Reply<R>: crate::RemoteSend,
            Reply<<R as IsPipelinableReply>::Pipelined>: crate::RemoteSend,
            Codec: codec::Codec
    }
}

/// Handle to obtain the result of [completing](PipelinableReplyTo::complete) a call.
///
/// Await this handle to obtain the result of transmitting the reply. This is optional
/// and only necessary if you want to explicitly handle errors that can occur while
/// sending.
///
/// You *should not* delay the receipt of further requests by awaiting this handle.
/// Dropping it *does not* abort transmitting the reply; a failure caused by the reply
/// itself, such as a serialization error, is logged in that case.
pub enum Completing<R>
where
    R: IsPipelinableReply,
{
    /// The reply of an ordinary call is being transmitted.
    Normal(Sending<Reply<R>>),
    /// The reply of a pipelined call is being transmitted.
    Pipeline(Sending<Reply<<R as IsPipelinableReply>::Pipelined>>),
}

impl<R> std::fmt::Debug for Completing<R>
where
    R: IsPipelinableReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal(_) => f.debug_tuple("Normal").finish(),
            Self::Pipeline(_) => f.debug_tuple("Pipeline").finish(),
        }
    }
}

impl<R> Future for Completing<R>
where
    R: IsPipelinableReply,
{
    type Output = Result<(), SendingError<<R as IsPipelinableReply>::Pipelined>>;

    fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Self::Output> {
        let res = match self.get_mut() {
            Self::Normal(sending) => ready!(sending.poll_unpin(cx))
                .map_err(|err| err.map_item(|reply| Into::<R>::into(reply).into_pipelined())),
            Self::Pipeline(sending) => ready!(sending.poll_unpin(cx))
                .map_err(|err| err.map_item(Into::<<R as IsPipelinableReply>::Pipelined>::into)),
        };
        Poll::Ready(res)
    }
}
