//! Sending the reply to a remote method call.

use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::{
    codec,
    rch::{Sending, oneshot},
};

/// The type a method's return value is transferred as.
///
/// This is a projection rather than the type itself, because the return type of
/// a method is taken as written in the trait, which may be an alias, and thus
/// cannot be taken apart by the [`remote`](super::remote) macro.
#[doc(hidden)]
pub type Reply<R> = <R as IsReply>::Compact;

/// A method return type, which is always a [`Result`].
#[doc(hidden)]
pub trait IsReply: Sized {
    /// The type the value is transferred as.
    type Compact: From<Self> + Into<Self>;
}

impl<T, E> IsReply for Result<T, E> {
    type Compact = crate::versioned::result::Result<T, E>;
}

/// Sends the reply to a remote method call.
///
/// This is the `__reply_tx` field of a request generated by the
/// [`remote`](super::remote) macro. Send the return value of the method to
/// reply to the call; dropping this without sending makes the call fail at the
/// caller.
pub struct ReplySender<R, Codec = codec::Default>(oneshot::Sender<Reply<R>, Codec>)
where
    R: IsReply;

/// Creates a channel for replying to a remote method call.
#[doc(hidden)]
pub fn reply_channel<R, Codec>(
    max_item_size: usize,
) -> (ReplySender<R, Codec>, oneshot::Receiver<Reply<R>, Codec>)
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    let (mut tx, rx) = oneshot::channel();
    tx.set_max_item_size(max_item_size);
    (ReplySender(tx), rx)
}

impl<R, Codec> std::fmt::Debug for ReplySender<R, Codec>
where
    R: IsReply,
{
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_struct("ReplySender").finish()
    }
}

impl<R, Codec> ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    /// Sends the reply over this channel.
    ///
    /// `Ok` means that the reply was queued for sending; the returned handle
    /// reports whether it was sent.
    pub fn send(self, reply: R) -> Result<Sending<Reply<R>>, oneshot::SendError<R>> {
        self.0.send(reply.into()).map_err(|err| match err {
            oneshot::SendError::Closed(reply) => oneshot::SendError::Closed(reply.into()),
            oneshot::SendError::Failed => oneshot::SendError::Failed,
        })
    }

    /// Completes when the caller is no longer interested in the reply, because
    /// the call was cancelled, the client was dropped or the connection failed.
    pub async fn closed(&self) {
        self.0.closed().await
    }

    /// Returns whether the caller is no longer interested in the reply.
    pub fn is_closed(&self) -> bool {
        self.0.is_closed()
    }

    /// The maximum size of the reply in bytes.
    ///
    /// A reply exceeding this is not sent.
    pub fn max_item_size(&self) -> usize {
        self.0.max_item_size()
    }
}

impl<R, Codec> Serialize for ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(serializer)
    }
}

impl<'de, R, Codec> Deserialize<'de> for ReplySender<R, Codec>
where
    R: IsReply,
    Reply<R>: crate::RemoteSend,
    Codec: codec::Codec,
{
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(Self(oneshot::Sender::deserialize(deserializer)?))
    }
}
