//! Verifies that a user can implement versioning for their own types.

use remoc::{
    rch::base::{StorageRef, storage_ref},
    versioned::{self, Versioned, Versioner},
};
use serde::{Deserialize, Serialize};

#[cfg(all(target_family = "wasm", feature = "js"))]
use wasm_bindgen_test::wasm_bindgen_test;

use crate::loop_channel;

/// Protocol version of the application, stored in the connection storage.
#[derive(Clone, Copy, Debug, PartialEq)]
struct ProtoVersion(u32);

/// Uses the old representation when the remote endpoint speaks version 1.
struct ProtoVersioner;

impl Versioner for ProtoVersioner {
    fn use_old() -> Result<bool, versioned::Error> {
        let version = remoc::rch::base::with_storage(|storage| storage.get::<ProtoVersion>())
            .flatten()
            .ok_or("protocol version is unknown")?;
        Ok(version.0 < 2)
    }
}

/// A user type whose representation changed between protocol versions.
///
/// Version 1 transferred the full name, version 2 transferred its parts
/// separately and added a new field.
#[derive(Debug, PartialEq)]
struct Person {
    first_name: String,
    last_name: String,
    age: u32,
}

#[derive(Serialize)]
struct PersonV2Ref<'a> {
    first_name: &'a String,
    last_name: &'a String,
    age: &'a u32,
}

#[derive(Deserialize)]
struct PersonV2 {
    first_name: String,
    last_name: String,
    age: u32,
}

#[derive(Serialize)]
struct PersonV1Ref {
    name: String,
}

#[derive(Deserialize)]
struct PersonV1 {
    name: String,
}

impl Versioned for Person {
    type Versioner = ProtoVersioner;

    type CurrentRef<'a> = PersonV2Ref<'a>;
    fn as_current<'a>(&'a self) -> Result<Self::CurrentRef<'a>, versioned::Error> {
        Ok(PersonV2Ref { first_name: &self.first_name, last_name: &self.last_name, age: &self.age })
    }

    type Current = PersonV2;
    fn from_current(current: Self::Current) -> Result<Self, versioned::Error> {
        Ok(Self { first_name: current.first_name, last_name: current.last_name, age: current.age })
    }

    type OldRef<'a> = PersonV1Ref;
    fn as_old<'a>(&'a self) -> Result<Self::OldRef<'a>, versioned::Error> {
        Ok(PersonV1Ref { name: format!("{} {}", self.first_name, self.last_name) })
    }

    type Old = PersonV1;
    fn from_old(old: Self::Old) -> Result<Self, versioned::Error> {
        let (first_name, last_name) = old.name.split_once(' ').ok_or("malformed name")?;
        // The age was not part of version 1.
        Ok(Self { first_name: first_name.to_string(), last_name: last_name.to_string(), age: 0 })
    }
}

remoc::impl_serde! { Person }

/// Message that establishes the protocol version and is never versioned itself.
#[derive(Serialize, Deserialize)]
struct Hello {
    version: u32,
    storage_ref: StorageRef,
}

#[derive(Serialize, Deserialize)]
enum Msg {
    Hello(Hello),
    Person(Person),
}

async fn exchange(remote_version: u32) -> Person {
    let ((mut a_tx, _), (_, mut b_rx)) = loop_channel::<Msg>().await;

    // The hello message is always backwards compatible and establishes the version.
    let (storage_ref, handle) = storage_ref();
    a_tx.send(Msg::Hello(Hello { version: remote_version, storage_ref })).await.unwrap();
    let sender_storage = handle.await.unwrap();
    sender_storage.insert(ProtoVersion(remote_version));

    let Msg::Hello(hello) = b_rx.recv().await.unwrap().unwrap() else { panic!("expected hello") };
    hello.storage_ref.get().unwrap().insert(ProtoVersion(hello.version));

    // Subsequent messages use the negotiated representation.
    a_tx.send(Msg::Person(Person { first_name: "Anna".to_string(), last_name: "Meyer".to_string(), age: 42 }))
        .await
        .unwrap();

    let Msg::Person(person) = b_rx.recv().await.unwrap().unwrap() else { panic!("expected person") };
    person
}

#[cfg_attr(not(all(target_family = "wasm", feature = "js")), tokio::test)]
#[cfg_attr(all(target_family = "wasm", feature = "js"), wasm_bindgen_test)]
async fn current_representation() {
    crate::init();

    let person = exchange(2).await;
    println!("version 2: {person:?}");
    assert_eq!(person, Person { first_name: "Anna".into(), last_name: "Meyer".into(), age: 42 });
}

#[cfg_attr(not(all(target_family = "wasm", feature = "js")), tokio::test)]
#[cfg_attr(all(target_family = "wasm", feature = "js"), wasm_bindgen_test)]
async fn old_representation() {
    crate::init();

    let person = exchange(1).await;
    println!("version 1: {person:?}");

    // Version 1 transferred the name as a whole and had no age field.
    assert_eq!(person, Person { first_name: "Anna".into(), last_name: "Meyer".into(), age: 0 });
}

/// Recovery of values that only a newer version of an application can decode.
///
/// The mechanism is generated by the same macro for every type that declares a
/// `recover` clause, thus one type stands for all of them.
mod recover {
    use futures::StreamExt;
    use remoc::{rch::base, versioned::compact::impl_enum};
    use serde::{Deserialize, Serialize};

    #[cfg(all(target_family = "wasm", feature = "js"))]
    use wasm_bindgen_test::wasm_bindgen_test;

    /// The status as a newer version of the application knows it.
    pub mod new {
        use super::*;

        #[derive(Debug, Clone, PartialEq)]
        pub enum Status {
            Ready,
            Busy(u32),
            /// Only known to this version.
            Overloaded(String),
            /// Stands for a status this version does not know.
            Unknown,
        }

        // The recovery clause belongs to the type and thus is declared by every
        // version of it.
        impl_enum! {
            Status,
            recover = Status::Unknown,
            variants {
                Ready => "_0",
                Busy(load: u32) => "_1",
                Overloaded(reason: String) => "_2",
                Unknown => "_50",
            }
        }

        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct Report {
            pub status: Status,
            pub note: String,
        }
    }

    /// The status as an older version of the application knows it.
    pub mod old {
        use super::*;

        #[derive(Debug, Clone, PartialEq)]
        pub enum Status {
            Ready,
            Busy(u32),
            /// Stands for a status this version does not know.
            Unknown,
        }

        impl_enum! {
            Status,
            recover = Status::Unknown,
            variants {
                Ready => "_0",
                Busy(load: u32) => "_1",
                Unknown => "_50",
            }
        }

        #[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
        pub struct Report {
            pub status: Status,
            pub note: String,
        }
    }

    /// Connects a sender of the newer version to a receiver of the older one.
    async fn across_versions() -> (base::Sender<new::Report>, base::Receiver<old::Report>) {
        crate::loop_transport!(0, a_tx, a_rx, b_tx, b_rx);
        let cfg = remoc::Cfg::default();

        let a =
            remoc::Connect::framed::<_, _, _, _, new::Report, (), remoc::codec::Default>(cfg.clone(), a_tx, a_rx);
        let b = remoc::Connect::framed::<_, _, _, _, (), old::Report, remoc::codec::Default>(cfg, b_tx, b_rx);
        let ((a_conn, a_tx, _a_rx), (b_conn, _b_tx, b_rx)) = futures::future::try_join(a, b).await.unwrap();

        wokio::spawn(async move {
            let _ = a_conn.await;
        });
        wokio::spawn(async move {
            let _ = b_conn.await;
        });

        (a_tx, b_rx)
    }

    /// A value that the receiving endpoint fully understands is transferred unchanged.
    #[cfg_attr(not(all(target_family = "wasm", feature = "js")), tokio::test)]
    #[cfg_attr(all(target_family = "wasm", feature = "js"), wasm_bindgen_test)]
    async fn known_variants_are_transferred() {
        crate::init();
        let (mut tx, mut rx) = across_versions().await;

        for (sent, expected) in
            [(new::Status::Ready, old::Status::Ready), (new::Status::Busy(7), old::Status::Busy(7))]
        {
            tx.send(new::Report { status: sent, note: "hello".to_string() }).await.unwrap();
            let received = rx.recv().await.unwrap().unwrap();
            assert_eq!(received, old::Report { status: expected, note: "hello".to_string() });
        }
    }

    /// A variant that the receiving endpoint does not know is recovered, and the value
    /// containing it stays decodable.
    #[cfg_attr(not(all(target_family = "wasm", feature = "js")), tokio::test)]
    #[cfg_attr(all(target_family = "wasm", feature = "js"), wasm_bindgen_test)]
    async fn unknown_variant_is_recovered() {
        crate::init();
        let (mut tx, mut rx) = across_versions().await;

        let sent = new::Report {
            status: new::Status::Overloaded("too many requests".to_string()),
            note: "keep this".to_string(),
        };
        tx.send(sent).await.unwrap();

        let received = rx.recv().await.unwrap().unwrap();
        assert_eq!(
            received.status,
            old::Status::Unknown,
            "an unknown variant was not replaced by the recovery value"
        );
        assert_eq!(received.note, "keep this", "the value containing the unknown variant was altered");
    }

    /// Recovery does not disturb the values transferred after it.
    #[cfg_attr(not(all(target_family = "wasm", feature = "js")), tokio::test)]
    #[cfg_attr(all(target_family = "wasm", feature = "js"), wasm_bindgen_test)]
    async fn recovery_does_not_break_the_channel() {
        crate::init();
        let (mut tx, mut rx) = across_versions().await;

        tx.send(new::Report { status: new::Status::Overloaded("gone".to_string()), note: "first".to_string() })
            .await
            .unwrap();
        tx.send(new::Report { status: new::Status::Busy(1), note: "second".to_string() }).await.unwrap();

        assert_eq!(rx.recv().await.unwrap().unwrap().status, old::Status::Unknown);
        let second = rx.recv().await.unwrap().unwrap();
        assert_eq!(second, old::Report { status: old::Status::Busy(1), note: "second".to_string() });
    }
}
