[package]
name = "pizzeria"
version = "0.1.0"
edition = "2024"

[dependencies]
remoc = { path = "../../../remoc" }
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-opentelemetry = "0.33"
opentelemetry = "0.32"
opentelemetry_sdk = "0.32"
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"] }
